name: sync-types
author: "@cobaltt7"
description: GitHub action to sync @types dependencies with the normal dependency version.
outputs:
    output-dir:
        description: "Output log directory"
        value: ${{ steps.output.outputs.output-dir }}
runs:
    using: composite
    steps:
        - name: Set output
          shell: bash
          id: output
          run: echo "output-dir=$GITHUB_ACTION_PATH" >> $GITHUB_OUTPUT

        - name: Setup Node.JS
          uses: actions/setup-node@v4.1.0
          with:
              node-version: 22.10.0
              cache: npm

        - name: Install
          shell: bash
          run: npm i
          working-directory: ${{ github.action_path }}

        - name: Copy lockfile
          shell: bash
          run: cp $GITHUB_WORKSPACE/package-lock.json $GITHUB_WORKSPACE/package-lock.old.json

        - name: Remove lockfile
          shell: bash
          run: rm $GITHUB_WORKSPACE/package-lock.json

        - name: Sync @types versions
          shell: bash
          run: node $GITHUB_ACTION_PATH/script.mjs "$GITHUB_ACTION_PATH" "$GITHUB_WORKSPACE"

        - name: Install
          shell: bash
          run: npm i
          working-directory: ${{ github.workspace }}

        - name: Find changes
          shell: bash
          run: node $GITHUB_ACTION_PATH/getChanges.mjs "$GITHUB_ACTION_PATH" "$GITHUB_WORKSPACE"
          continue-on-error: true

        - name: Emit output file
          shell: bash
          run: echo "$(cat $GITHUB_ACTION_PATH/changes.md)$(cat $GITHUB_ACTION_PATH/sync.md)" > $GITHUB_ACTION_PATH/output.md

        - name: Remove backup lockfile
          shell: bash
          run: rm $GITHUB_WORKSPACE/package-lock.old.json
